updated yaml file for worker 2

diff --git a/.github/workflows/historical_scraper.yml b/.github/workflows/historical_scraper.yml
--- a/.github/workflows/historical_scraper.yml
+++ b/.github/workflows/historical_scraper.yml
@@ -2,8 +2,8 @@ name: Historical Stats Scraper
 
 on:
   workflow_dispatch:
-#  schedule:
-#    - cron: "*/30 * * * *" # This schedules the workflow to every 20 minutes
+  schedule:
+    - cron: "*/30 * * * *" # This schedules the workflow to run every 30 minutes
 
 jobs:
   run-script:
@@ -21,9 +21,6 @@ jobs:
       - name: Install requirements
         run: pip install -r requirements.txt
 
-#      - name: Debug
-#        run: ls ./scraper/historical
-
       - name: Run Python Script
         run: python main.py
 
@@ -32,19 +29,22 @@ jobs:
           git config user.name "github-actions[bot]"
           git config user.email "github-actions[bot]@users.noreply.github.com"
 
-      - name: Fetch and Pull Latest Changes
-        run: |
-          git fetch origin
-          git pull origin main --rebase # Rebase to avoid merge commits
-
-      - name: Commit and Push Changes
+      - name: Commit, pull and Push Changes
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
-          # Add all generated CSV files
-          git add ./scraping/historical/state_2.json
-          git add ./shared/data/historical/**/*.csv
-          # Commit with a message
-          git commit -m "Update scraped data [skip ci]" || echo "No changes to commit"
-          # Push the changes
-          git push
+           # Add all generated CSV files and commit
+            git add .
+            git commit -m "Update scraped data [skip ci]" || echo "No changes to commit"
+            
+            # Stash uncommitted changes (if any)
+            git stash save "Auto-stash before pull" || echo "Nothing to stash"
+            
+            # Pull the latest changes
+            git pull origin main --rebase || (echo "Pull failed" && exit 1)
+          
+            # Apply stashed changes (if any)
+            git stash pop || echo "No stash to apply"
+              
+            # Push changes back to the repository
+            git push origin main || (echo "Push failed" && exit 1)
